apiVersion: v1
baseDomain: abc-bah12.k8slab.org
compute:
- name: worker
  hyperthreading: Enabled
  replicas: 0
controlPlane:
  name: master
  replicas: 1
  architecture: amd64
  hyperthreading: Enabled
  platform:
    aws:
      type: c5a.12xlarge
      rootVolume:
        size: 300
        type: gp3
metadata:
  name: abc-bah12
platform:
  aws:
    region: me-south-1
    userTags:
      owner: "walid.shaari@linux.com"
      team: "wwps sa"
      usage: "Dev"
      description: "Product Development and Demo environment for OpenShift SNO"
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":...}}}'
sshKey: 'ssh-rsa ...'
